import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import type { GameState, SessionUser } from './types.js';
import { config } from './config.js';

export type Preferences = { notifications: boolean; sound: boolean; theme: 'midnight' | 'table' | 'cyber' };
export type ProfileStats = { gamesPlayed: number; wins: number; losses: number; winRate: number; currentStreak: number; longestStreak: number; unoCalls: number; caughtWithoutUno: number };
export type Account = SessionUser & { emailCiphertext: string; emailHash: string; passwordHash: string; bio?: string; country?: string; avatarPreset?: string; preferences: Preferences; sessionVersion: number; createdAt: string };
export type AccountInput = SessionUser & { emailCiphertext: string; emailHash: string; passwordHash: string; bio?: string; country?: string; avatarPreset?: string; preferences?: Preferences; sessionVersion?: number; createdAt: string };
export type Profile = { username: string; avatarUrl?: string; avatarPreset?: string; bio?: string; country?: string; stats: ProfileStats; preferences: Preferences; achievements: string[]; createdAt: string };
export type PublicProfile = Pick<Profile, 'username' | 'avatarUrl' | 'avatarPreset' | 'bio' | 'country' | 'stats' | 'achievements'>;
export type Friend = { id: string; username: string; avatarUrl?: string; avatarPreset?: string; isOnline?: boolean; stats: Pick<ProfileStats, 'wins' | 'losses'> };
export type MatchSummary = { id: string; roomCode: string; winnerId: string; completedAt: string; players: { id: string; username: string; score: number }[] };
export type ProfileUpdate = { username: string; bio?: string; country?: string; avatarUrl?: string; avatarPreset?: string; preferences?: Preferences };

const prefs = (): Preferences => ({ notifications: true, sound: true, theme: 'midnight' });
const blank = (): ProfileStats => ({ gamesPlayed: 0, wins: 0, losses: 0, winRate: 0, currentStreak: 0, longestStreak: 0, unoCalls: 0, caughtWithoutUno: 0 });
const rate = (stats: ProfileStats) => ({ ...stats, winRate: stats.gamesPlayed ? Math.round((stats.wins / stats.gamesPlayed) * 100) : 0 });
const badges = (s: ProfileStats) => [
  ...(s.wins >= 1 ? ['First Win'] : []),
  ...(s.longestStreak >= 3 ? ['Hot Streak'] : []),
  ...(s.longestStreak >= 5 ? ['Unstoppable'] : []),
  ...(s.unoCalls >= 10 ? ['UNO Master'] : []),
  ...(s.gamesPlayed >= 25 ? ['Table Regular'] : []),
  ...(s.caughtWithoutUno >= 3 ? ['Hawk Eye'] : []),
  ...(s.gamesPlayed >= 100 ? ['Century Club'] : [])
];
const asProfile = (a: Account, stats: ProfileStats): Profile => ({ username: a.username, avatarUrl: a.avatarUrl, avatarPreset: a.avatarPreset, bio: a.bio, country: a.country, stats, preferences: a.preferences ?? prefs(), achievements: badges(stats), createdAt: a.createdAt });

export interface Repository {
  createAccount(a: AccountInput): Promise<void>; findAccountByEmailHash(hash: string): Promise<Account | undefined>; findAccountById(id: string): Promise<Account | undefined>;
  getProfile(id: string): Promise<Profile | undefined>; getPublicProfile(username: string): Promise<PublicProfile | undefined>; updateProfile(id: string, data: ProfileUpdate): Promise<Account>;
  updateCredentials(id: string, data: { emailCiphertext?: string; emailHash?: string; passwordHash?: string }): Promise<Account>; bumpSessionVersion(id: string): Promise<void>; isSessionVersionCurrent(id: string, version: number): Promise<boolean>; deleteAccount(id: string): Promise<void>;
  addFriend(id: string, username: string): Promise<void>; removeFriend(id: string, username: string): Promise<void>; friends(id: string): Promise<Friend[]>;
  leaderboard(limit: number): Promise<{ id: string; username: string; wins: number; losses: number; rating: number; avatarUrl?: string; avatarPreset?: string }[]>; history(id: string, limit: number): Promise<MatchSummary[]>; exportData(id: string): Promise<{ profile: Profile; matches: MatchSummary[] } | undefined>;
  saveCompletedMatch(state: GameState): Promise<void>; createReport(input: { reporterId: string; category: string; details: string; roomCode?: string }): Promise<void>; close(): Promise<void>;
}

export class MemoryRepository implements Repository {
  private byEmail = new Map<string, Account>(); private byId = new Map<string, Account>(); private stats = new Map<string, ProfileStats>(); private matches: MatchSummary[] = []; private links = new Set<string>(); private reports: unknown[] = [];
  private account(id: string) { const a = this.byId.get(id); if (!a) throw new Error('Account not found.'); return a; }
  private stat(id: string) { const current = this.stats.get(id); if (current) return rate(current); const created = blank(); this.stats.set(id, created); return created; }
  private byName(username: string) { return [...this.byId.values()].find((a) => a.username.toLowerCase() === username.toLowerCase()); }
  private unique(username: string, except?: string) { if (this.byName(username)?.id !== except && this.byName(username)) throw new Error('That username is already taken.'); }
  async createAccount(a: AccountInput) { if (this.byEmail.has(a.emailHash)) throw new Error('An account already exists for that email.'); this.unique(a.username); const account: Account = { ...a, preferences: a.preferences ?? prefs(), sessionVersion: a.sessionVersion ?? 0 }; this.byEmail.set(account.emailHash, account); this.byId.set(account.id, account); this.stat(account.id); }
  async findAccountByEmailHash(hash: string) { return this.byEmail.get(hash); } async findAccountById(id: string) { return this.byId.get(id); }
  async getProfile(id: string) { const a = this.byId.get(id); const s = this.stat(id); return a ? asProfile(a, s) : { username: 'Guest Player', stats: s, preferences: prefs(), achievements: badges(s), createdAt: new Date().toISOString() }; }
  async getPublicProfile(username: string) { const a = this.byName(username); if (!a || a.isGuest) return undefined; const p = asProfile(a, this.stat(a.id)); return { username: p.username, avatarUrl: p.avatarUrl, avatarPreset: p.avatarPreset, bio: p.bio, country: p.country, stats: p.stats, achievements: p.achievements }; }
  async updateProfile(id: string, data: ProfileUpdate) { const a = this.account(id); this.unique(data.username, id); Object.assign(a, { username: data.username, bio: data.bio || undefined, country: data.country || undefined, avatarUrl: data.avatarUrl !== undefined ? (data.avatarUrl || undefined) : a.avatarUrl, avatarPreset: data.avatarPreset !== undefined ? (data.avatarPreset || undefined) : a.avatarPreset, preferences: data.preferences ?? a.preferences ?? prefs() }); return a; }
  async updateCredentials(id: string, data: { emailCiphertext?: string; emailHash?: string; passwordHash?: string }) { const a = this.account(id); if (data.emailHash && data.emailHash !== a.emailHash) { if (this.byEmail.has(data.emailHash)) throw new Error('An account already exists for that email.'); this.byEmail.delete(a.emailHash); a.emailHash = data.emailHash; this.byEmail.set(a.emailHash, a); } if (data.emailCiphertext) a.emailCiphertext = data.emailCiphertext; if (data.passwordHash) a.passwordHash = data.passwordHash; return a; }
  async bumpSessionVersion(id: string) { this.account(id).sessionVersion = (this.account(id).sessionVersion ?? 0) + 1; } async isSessionVersionCurrent(id: string, v: number) { const a = this.byId.get(id); return a ? (a.sessionVersion ?? 0) === v : false; }
  async deleteAccount(id: string) { const a = this.account(id); this.byId.delete(id); this.byEmail.delete(a.emailHash); this.stats.delete(id); for (const key of this.links) if (key.split(':').includes(id)) this.links.delete(key); }
  async addFriend(id: string, username: string) { const target = this.byName(username); if (!target) throw new Error('Player not found.'); if (target.id === id) throw new Error('You cannot add yourself.'); this.links.add([id, target.id].sort().join(':')); }
  async removeFriend(id: string, username: string) { const target = this.byName(username); if (target) this.links.delete([id, target.id].sort().join(':')); }
  async friends(id: string) { return [...this.links].flatMap((key) => { const [one, two] = key.split(':'); if (one !== id && two !== id) return []; const a = this.byId.get(one === id ? two : one); if (!a) return []; const s = this.stat(a.id); return [{ id: a.id, username: a.username, avatarUrl: a.avatarUrl, avatarPreset: a.avatarPreset, stats: { wins: s.wins, losses: s.losses } }]; }).sort((a, b) => a.username.localeCompare(b.username)); }
  async leaderboard(limit: number) { return [...this.byId.values()].filter((a) => !a.isGuest).map((a) => { const s = this.stat(a.id); return { id: a.id, username: a.username, avatarUrl: a.avatarUrl, avatarPreset: a.avatarPreset, wins: s.wins, losses: s.losses, rating: 1000 + s.wins * 25 - s.losses * 10 }; }).sort((a, b) => b.rating - a.rating).slice(0, limit); }
  async history(id: string, limit: number) { return this.matches.filter((m) => m.players.some((p) => p.id === id)).slice(0, limit); }
  async exportData(id: string) { const profile = await this.getProfile(id); return profile ? { profile, matches: await this.history(id, 50) } : undefined; }
  async saveCompletedMatch(state: GameState) { if (!state.winnerId) return; this.matches.unshift({ id: randomUUID(), roomCode: state.roomId, winnerId: state.winnerId, completedAt: new Date().toISOString(), players: state.players.map((p) => ({ id: p.id, username: p.username, score: p.score })) }); for (const p of state.players) { if (p.isBot) continue; const s = this.stat(p.id); const won = p.id === state.winnerId; s.gamesPlayed++; s.wins += won ? 1 : 0; s.losses += won ? 0 : 1; s.currentStreak = won ? s.currentStreak + 1 : 0; s.longestStreak = Math.max(s.longestStreak, s.currentStreak); const m = state.matchMetrics.get(p.id); s.unoCalls += m?.unoCalls ?? 0; s.caughtWithoutUno += m?.caughtWithoutUno ?? 0; this.stats.set(p.id, rate(s)); } }
  async createReport(input: { reporterId: string; category: string; details: string; roomCode?: string }) { this.reports.push(input); } async close() {}
}

export class PostgresRepository implements Repository {
  private pool: Pool; constructor(url: string) { this.pool = new Pool({ connectionString: url, ssl: config.databaseSsl ? { rejectUnauthorized: false } : undefined }); }
  private fields = 'id, username, avatar_url AS "avatarUrl", avatar_preset AS "avatarPreset", bio, country, preferences, email_ciphertext AS "emailCiphertext", email_hash AS "emailHash", password_hash AS "passwordHash", session_version AS "sessionVersion", created_at AS "createdAt", false AS "isGuest"';
  private async one(sql: string, values: unknown[]) { return (await this.pool.query<Account>(sql, values)).rows[0]; }
  private async stat(id: string) { const row = (await this.pool.query<Omit<ProfileStats, 'winRate'>>('SELECT games_played AS "gamesPlayed", wins, losses, current_streak AS "currentStreak", longest_streak AS "longestStreak", uno_calls AS "unoCalls", caught_without_uno AS "caughtWithoutUno" FROM player_stats WHERE user_id=$1', [id])).rows[0]; return row ? rate({ ...row, winRate: 0 } as ProfileStats) : blank(); }
  async createAccount(a: AccountInput) { const r = await this.pool.query('INSERT INTO app_users (id, username, avatar_url, avatar_preset, bio, country, preferences, email_ciphertext, email_hash, password_hash, session_version) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 WHERE NOT EXISTS (SELECT 1 FROM app_users WHERE email_hash=$9 OR lower(username)=lower($2))', [a.id, a.username, a.avatarUrl ?? null, a.avatarPreset ?? null, a.bio ?? null, a.country ?? null, a.preferences ?? prefs(), a.emailCiphertext, a.emailHash, a.passwordHash, a.sessionVersion ?? 0]); if (!r.rowCount) throw new Error('That email or username is already in use.'); }
  async findAccountByEmailHash(hash: string) { return this.one(`SELECT ${this.fields} FROM app_users WHERE email_hash=$1`, [hash]); } async findAccountById(id: string) { return this.one(`SELECT ${this.fields} FROM app_users WHERE id=$1`, [id]); }
  async getProfile(id: string) { const a = await this.findAccountById(id); return a ? asProfile(a, await this.stat(id)) : undefined; }
  async getPublicProfile(name: string) { const a = await this.one(`SELECT ${this.fields} FROM app_users WHERE lower(username)=lower($1)`, [name]); if (!a) return undefined; const p = asProfile(a, await this.stat(a.id)); return { username: p.username, avatarUrl: p.avatarUrl, avatarPreset: p.avatarPreset, bio: p.bio, country: p.country, stats: p.stats, achievements: p.achievements }; }
  async updateProfile(id: string, d: ProfileUpdate) { const current = await this.findAccountById(id); if (!current) throw new Error('Account not found.'); const a = await this.one(`UPDATE app_users SET username=$2,bio=$3,country=$4,avatar_url=$5,avatar_preset=$6,preferences=$7 WHERE id=$1 AND NOT EXISTS (SELECT 1 FROM app_users x WHERE x.id<>$1 AND lower(x.username)=lower($2)) RETURNING ${this.fields}`, [id, d.username, d.bio ?? null, d.country ?? null, d.avatarUrl !== undefined ? (d.avatarUrl || null) : current.avatarUrl, d.avatarPreset !== undefined ? (d.avatarPreset || null) : current.avatarPreset, d.preferences ?? current.preferences ?? prefs()]); if (!a) throw new Error('That username is already taken.'); return a; }
  async updateCredentials(id: string, d: { emailCiphertext?: string; emailHash?: string; passwordHash?: string }) { const current = await this.findAccountById(id); if (!current) throw new Error('Account not found.'); const a = await this.one(`UPDATE app_users SET email_ciphertext=$2,email_hash=$3,password_hash=$4 WHERE id=$1 AND ($3=email_hash OR NOT EXISTS (SELECT 1 FROM app_users x WHERE x.id<>$1 AND x.email_hash=$3)) RETURNING ${this.fields}`, [id, d.emailCiphertext ?? current.emailCiphertext, d.emailHash ?? current.emailHash, d.passwordHash ?? current.passwordHash]); if (!a) throw new Error('An account already exists for that email.'); return a; }
  async bumpSessionVersion(id: string) { await this.pool.query('UPDATE app_users SET session_version=session_version+1 WHERE id=$1', [id]); } async isSessionVersionCurrent(id: string, v: number) { return Boolean((await this.pool.query('SELECT 1 FROM app_users WHERE id=$1 AND session_version=$2', [id, v])).rowCount); }
  async deleteAccount(id: string) { await this.pool.query('DELETE FROM app_users WHERE id=$1', [id]); }
  async addFriend(id: string, name: string) { const target = await this.one(`SELECT ${this.fields} FROM app_users WHERE lower(username)=lower($1)`, [name]); if (!target) throw new Error('Player not found.'); if (target.id === id) throw new Error('You cannot add yourself.'); const [low, high] = [id, target.id].sort(); await this.pool.query('INSERT INTO friendships (user_low,user_high) VALUES ($1,$2) ON CONFLICT DO NOTHING', [low, high]); }
  async removeFriend(id: string, name: string) { const target = await this.one(`SELECT ${this.fields} FROM app_users WHERE lower(username)=lower($1)`, [name]); if (target) { const [low, high] = [id, target.id].sort(); await this.pool.query('DELETE FROM friendships WHERE user_low=$1 AND user_high=$2', [low, high]); } }
  async friends(id: string) { const rows = (await this.pool.query<Friend & { wins: number; losses: number }>('SELECT u.id,u.username,u.avatar_url AS "avatarUrl",u.avatar_preset AS "avatarPreset",COALESCE(s.wins,0) AS wins,COALESCE(s.losses,0) AS losses FROM friendships f JOIN app_users u ON u.id=CASE WHEN f.user_low=$1 THEN f.user_high ELSE f.user_low END LEFT JOIN player_stats s ON s.user_id=u.id WHERE f.user_low=$1 OR f.user_high=$1 ORDER BY u.username', [id])).rows; return rows.map((r) => ({ id: r.id, username: r.username, avatarUrl: r.avatarUrl, avatarPreset: r.avatarPreset, stats: { wins: Number(r.wins), losses: Number(r.losses) } })); }
  async leaderboard(limit: number) { return (await this.pool.query<{ id: string; username: string; avatarUrl?: string; avatarPreset?: string; wins: number; losses: number; rating: number }>('SELECT u.id,u.username,u.avatar_url AS "avatarUrl",u.avatar_preset AS "avatarPreset",s.wins,s.losses,s.rating FROM leaderboard l JOIN app_users u ON u.id=l.id JOIN player_stats s ON s.user_id=u.id ORDER BY s.rating DESC LIMIT $1', [limit])).rows; }
  async history(id: string, limit: number) { const rows = (await this.pool.query<{ id: string; room_code: string; winner_id: string; completed_at: string; players: MatchSummary['players'] }>('SELECT m.id,m.room_code,m.winner_id,m.completed_at,json_agg(json_build_object(\'id\',mp.user_id,\'username\',mp.username,\'score\',mp.score)) AS players FROM matches m JOIN match_players mp ON mp.match_id=m.id WHERE EXISTS(SELECT 1 FROM match_players me WHERE me.match_id=m.id AND me.user_id=$1) GROUP BY m.id ORDER BY m.completed_at DESC LIMIT $2', [id, limit])).rows; return rows.map((r) => ({ id: r.id, roomCode: r.room_code, winnerId: r.winner_id, completedAt: r.completed_at, players: r.players })); }
  async exportData(id: string) { const profile = await this.getProfile(id); return profile ? { profile, matches: await this.history(id, 50) } : undefined; }
  async saveCompletedMatch(state: GameState) { if (!state.winnerId) return; const c = await this.pool.connect(); try { await c.query('BEGIN'); const match = randomUUID(); await c.query('INSERT INTO matches (id,room_code,winner_id,rounds) VALUES ($1,$2,$3,$4)', [match, state.roomId, state.winnerId, state.round]); for (const p of state.players) { await c.query('INSERT INTO match_players (match_id,user_id,username,score) VALUES ($1,$2,$3,$4)', [match, p.id, p.username, p.score]); if (!p.isGuest) { const won = p.id === state.winnerId; const m = state.matchMetrics.get(p.id); await c.query('INSERT INTO player_stats (user_id,games_played,wins,losses,rating,current_streak,longest_streak,uno_calls,caught_without_uno) VALUES ($1,1,$2,$3,$4,$5,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET games_played=player_stats.games_played+1,wins=player_stats.wins+EXCLUDED.wins,losses=player_stats.losses+EXCLUDED.losses,rating=player_stats.rating+EXCLUDED.rating,current_streak=CASE WHEN EXCLUDED.wins=1 THEN player_stats.current_streak+1 ELSE 0 END,longest_streak=GREATEST(player_stats.longest_streak,CASE WHEN EXCLUDED.wins=1 THEN player_stats.current_streak+1 ELSE 0 END),uno_calls=player_stats.uno_calls+EXCLUDED.uno_calls,caught_without_uno=player_stats.caught_without_uno+EXCLUDED.caught_without_uno,updated_at=now()', [p.id, won ? 1 : 0, won ? 0 : 1, won ? 25 : -10, won ? 1 : 0, m?.unoCalls ?? 0, m?.caughtWithoutUno ?? 0]); } } await c.query('COMMIT'); } catch (e) { await c.query('ROLLBACK'); throw e; } finally { c.release(); } }
  async createReport(input: { reporterId: string; category: string; details: string; roomCode?: string }) { await this.pool.query('INSERT INTO abuse_reports (id,reporter_id,room_code,category,details) VALUES ($1,$2,$3,$4,$5)', [randomUUID(), input.reporterId, input.roomCode ?? null, input.category, input.details]); } async close() { await this.pool.end(); }
}
export const repository: Repository = config.databaseUrl ? new PostgresRepository(config.databaseUrl) : new MemoryRepository();

